import java.util.Scanner;

/*
 * This Java source file was generated by the Gradle 'init' task.
 */
public class App {

    public static void main(String[] args) {
        App app = new App();
        String fromUnitName = null;
        String toUnitName = null;
        String unitNames = ITUnits.getUnitNames();
        Scanner scanner = new Scanner(System.in);
        System.out.println("amount?");
        int valueToConvert = Integer.valueOf(scanner.nextLine());
        do {
            System.out.println("fromuint "+unitNames);
            fromUnitName = scanner.nextLine();
        } while (!validateFromUnit(fromUnitName));
        ITUnits fromUnit = ITUnits.getUnit(fromUnitName);
        do {
            System.out.println("tounit? " + unitNames);
            toUnitName = scanner.nextLine();
        } while (!app.validateToUnit(toUnitName,fromUnit));
        ITUnits toUnit = ITUnits.getUnit(toUnitName);
        System.out.println("result " + valueToConvert*toUnit.getBits());
    }




    boolean validateToUnit(String toUnitName, ITUnits fromUnit) {
        for (ITUnits unit: ITUnits.values()) {
            if (unit.name().equals(toUnitName)){
                return true;
            }
        }
        return false;
    }

    private static boolean validateFromUnit(String fromUnit) {
        for (ITUnits unit: ITUnits.values()) {
            if (unit.name().equals(fromUnit)){
                return true;
            }
        }
        return false;
    }





}
